In [72]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os
import ehrauto

In [73]:
load_dotenv()

True

In [74]:
host=os.getenv("DB_HOST")
user=os.getenv("DB_USER")
password=os.getenv("DB_PASSWORD")
database=os.getenv("DB_NAME")

engine=create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{database}")

In [75]:
df=pd.read_sql("SELECT * FROM providers", engine)
df

                                       Id  ... PROCEDURES
0    00be71ce-3027-3878-86a9-fa73c047300c  ...          0
1    02441381-0110-32e8-b80d-ef580fe874d6  ...          0
2    02732025-956c-35fe-9f11-31f42226ec52  ...          0
3    060de5d5-8b70-3f1f-9be2-0b2e1a646d87  ...          0
4    0717988f-344c-3633-9a57-6da007df9606  ...          0
..                                    ...  ...        ...
248  f9e67288-2cdb-30f6-a899-a2a344537abb  ...          0
249  fa4c3c1e-91cc-3ab8-a2d4-9fe7f6fb572f  ...          0
250  fb78cf38-c23a-39d6-a704-a32c30c27217  ...          0
251  fc62d25a-02a2-3291-83fd-1ff2a17a82f8  ...          0
252  fe124ccd-c7c3-351c-8228-56dd6f4253e1  ...          0

[253 rows x 13 columns]

In [76]:
df["NAME"]=df["NAME"].str.replace('[^a-zA-Z]', ' ', regex=True)
df["NAME"]

0             Dinah    Kub
1           Leo    Strosin
2       Cira    Jakubowski
3      Enriqueta    Barton
4            Jon    Keeling
                ...
248         Sulema    Ryan
249         Tambra   Nolan
250          Amos    Bogan
251      Man    Balistreri
252       Niesha   Friesen
Name: NAME, Length: 253, dtype: str

In [77]:
df["NAME"]=df["NAME"].str.replace('    ', ' ')
df["NAME"]

0             Dinah Kub
1           Leo Strosin
2       Cira Jakubowski
3      Enriqueta Barton
4            Jon Keeling
              ...
248         Sulema Ryan
249      Tambra   Nolan
250          Amos Bogan
251      Man Balistreri
252    Niesha   Friesen
Name: NAME, Length: 253, dtype: str

In [78]:
df

                                       Id  ... PROCEDURES
0    00be71ce-3027-3878-86a9-fa73c047300c  ...          0
1    02441381-0110-32e8-b80d-ef580fe874d6  ...          0
2    02732025-956c-35fe-9f11-31f42226ec52  ...          0
3    060de5d5-8b70-3f1f-9be2-0b2e1a646d87  ...          0
4    0717988f-344c-3633-9a57-6da007df9606  ...          0
..                                    ...  ...        ...
248  f9e67288-2cdb-30f6-a899-a2a344537abb  ...          0
249  fa4c3c1e-91cc-3ab8-a2d4-9fe7f6fb572f  ...          0
250  fb78cf38-c23a-39d6-a704-a32c30c27217  ...          0
251  fc62d25a-02a2-3291-83fd-1ff2a17a82f8  ...          0
252  fe124ccd-c7c3-351c-8228-56dd6f4253e1  ...          0

[253 rows x 13 columns]

In [79]:
df=df.drop(columns=["LAT", "LON"])

In [80]:
df

                                       Id  ... PROCEDURES
0    00be71ce-3027-3878-86a9-fa73c047300c  ...          0
1    02441381-0110-32e8-b80d-ef580fe874d6  ...          0
2    02732025-956c-35fe-9f11-31f42226ec52  ...          0
3    060de5d5-8b70-3f1f-9be2-0b2e1a646d87  ...          0
4    0717988f-344c-3633-9a57-6da007df9606  ...          0
..                                    ...  ...        ...
248  f9e67288-2cdb-30f6-a899-a2a344537abb  ...          0
249  fa4c3c1e-91cc-3ab8-a2d4-9fe7f6fb572f  ...          0
250  fb78cf38-c23a-39d6-a704-a32c30c27217  ...          0
251  fc62d25a-02a2-3291-83fd-1ff2a17a82f8  ...          0
252  fe124ccd-c7c3-351c-8228-56dd6f4253e1  ...          0

[253 rows x 11 columns]

In [81]:
df2=pd.read_sql("SELECT * FROM patients",engine)
df2

                                       Id  ...    INCOME
0    06bf1603-10a3-9788-ab91-0701da9495b9  ...   65537.0
1    0826c4e7-e2ca-a5ec-bd7b-119397bb2046  ...    2670.0
2    0ca05b00-82dc-4b42-348c-b9d58be9e632  ...   25061.0
3    0f1b4b7a-73a0-eb63-5bd7-f55ae3136b1c  ...  104523.0
4    0fb8cfe4-89bb-e3a6-e9eb-3a3a34e9a2a7  ...   58184.0
..                                    ...  ...       ...
102  f7b800ed-1884-d158-f114-915726bddc48  ...  108214.0
103  f954f902-0b3f-eb41-0b90-fbd520e7739c  ...   71516.0
104  fbf1cb7c-17e4-bcce-6d1c-04f9ae7149c8  ...  100439.0
105  fc54c463-0e69-2416-3d11-0b2e5bab9468  ...   89770.0
106  fdaef9b1-877f-4539-6a09-b3a9c852be39  ...   98218.0

[107 rows x 28 columns]

In [82]:
ehrauto.standardizenames(df2, "FIRST")

                                       Id  ...    INCOME
0    06bf1603-10a3-9788-ab91-0701da9495b9  ...   65537.0
1    0826c4e7-e2ca-a5ec-bd7b-119397bb2046  ...    2670.0
2    0ca05b00-82dc-4b42-348c-b9d58be9e632  ...   25061.0
3    0f1b4b7a-73a0-eb63-5bd7-f55ae3136b1c  ...  104523.0
4    0fb8cfe4-89bb-e3a6-e9eb-3a3a34e9a2a7  ...   58184.0
..                                    ...  ...       ...
102  f7b800ed-1884-d158-f114-915726bddc48  ...  108214.0
103  f954f902-0b3f-eb41-0b90-fbd520e7739c  ...   71516.0
104  fbf1cb7c-17e4-bcce-6d1c-04f9ae7149c8  ...  100439.0
105  fc54c463-0e69-2416-3d11-0b2e5bab9468  ...   89770.0
106  fdaef9b1-877f-4539-6a09-b3a9c852be39  ...   98218.0

[107 rows x 28 columns]

In [83]:
ehrauto.standardizenames(df2,"LAST")

                                       Id  ...    INCOME
0    06bf1603-10a3-9788-ab91-0701da9495b9  ...   65537.0
1    0826c4e7-e2ca-a5ec-bd7b-119397bb2046  ...    2670.0
2    0ca05b00-82dc-4b42-348c-b9d58be9e632  ...   25061.0
3    0f1b4b7a-73a0-eb63-5bd7-f55ae3136b1c  ...  104523.0
4    0fb8cfe4-89bb-e3a6-e9eb-3a3a34e9a2a7  ...   58184.0
..                                    ...  ...       ...
102  f7b800ed-1884-d158-f114-915726bddc48  ...  108214.0
103  f954f902-0b3f-eb41-0b90-fbd520e7739c  ...   71516.0
104  fbf1cb7c-17e4-bcce-6d1c-04f9ae7149c8  ...  100439.0
105  fc54c463-0e69-2416-3d11-0b2e5bab9468  ...   89770.0
106  fdaef9b1-877f-4539-6a09-b3a9c852be39  ...   98218.0

[107 rows x 28 columns]