In [4]:
import pandas as pd

In [ ]:
df =pd.read_csv(r"C:\Users\lunas\Downloads\world_population.csv")

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [15]:
pd.set_option('display.max_rows', 10)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  227 non-null    str
 1   Region   227 non-null    str
dtypes: str(2)
memory usage: 3.7 KB

In [18]:
df.shape

(227, 2)

In [19]:
df.head(10)

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES

In [20]:
df['Country']

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
222         West Bank
223    Western Sahara
224             Yemen
225            Zambia
226          Zimbabwe
Name: Country, Length: 227, dtype: str

In [21]:
df.loc[224]

Country                                 Yemen
Region     NEAR EAST
Name: 224, dtype: str

In [22]:
df.iloc[224]

Country                                 Yemen
Region     NEAR EAST
Name: 224, dtype: str